version: "3.4"
services:
  traefik:
    image: traefik:v2.4
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  api:
    build:
      context: .
      target: development
    restart: unless-stopped
    ports:
      - "80"
      - "8736:8736"
    volumes:
      - ./:/app
      - ~/.aws:/root/.aws
      - ./certs:/certs
      - ~/.vsdbg:/remote_debugger:rw
    environment:
      CONFIGURATION: Debug
      ASPNETCORE_HOSTINGSTARTUPASSEMBLIES: Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation
      ASPNETCORE_ENVIRONMENT: Development
      Database__Host: db
      Database__Name: ${DB_NAME}
      Database__User: ${DB_USER}
      Database__Password: ${DB_PASSWORD}
      EncryptionOptions__KmsKeyId: ${ENCRYPTION_KEY_ID}
      AWS_REGION: us-east-1
      Auth__DomainName: localhost
      Auth__CookieDomain: localhost
      App__UseHttps: "false"
    labels:
      - traefik.enable=true
      - traefik.http.routers.adapter.rule=Host(`localhost`)
      - traefik.http.routers.adapter.entrypoints=web
      - traefik.http.services.adapter.loadbalancer.server.scheme=h2c

  db:
    image: mariadb/server:10.4
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
