version: "3.4"
services:
  api:
    build:
      context: .
      target: development
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/app
      - ~/.aws:/root/.aws
      - ./certs:/certs
      - ~/.vsdbg:/remote_debugger:rw
    environment:
      CONFIGURATION: Debug
      OpenId__DomainName: localhost
      Database__Host: db
      Database__Name: ${DB_NAME}
      Database__User: ${DB_USER}
      Database__Password: ${DB_PASSWORD}
      EncryptionOptions__KmsKeyId: ${ENCRYPTION_KEY_ID}
      AWS_REGION: us-east-1

  db:
    image: mariadb/server:10.4
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
