version: "3.4"
services:
  traefik:
    image: traefik:v2.9
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  api:
    image: brighid/identity
    working_dir: /app
    restart: unless-stopped
    platform: linux/arm64
    ports:
      - "80"
      - "8736:8736"
    volumes:
      - ./bin/Server/Debug/linux-musl-arm64:/app
      - ./bin/Interface/Debug/publish/wwwroot:/wwwroot
      - ~/.aws:/home/brighid/.aws
      - ~/.vsdbg:/remote_debugger:rw
    environment:
      AWS_REGION: us-east-1
      CONFIGURATION: Debug
      DECRYPTION_DISABLED: "true"
      ASPNETCORE_HOSTINGSTARTUPASSEMBLIES: Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation
      AWS_XRAY_DAEMON_ADDRESS: xray:2000
      AWS_XRAY_TRACING_NAME: Identity
      AWS_XRAY_CONTEXT_MISSING: LOG_ERROR
      Environment: local
      Database__Host: db
      Database__Name: ${DB_NAME}
      Database__User: ${DB_USER}
      Database__Password: ${DB_PASSWORD}
      EncryptionOptions__KmsKeyId: ${ENCRYPTION_KEY_ID}
      Auth__DomainName: localhost
      Auth__CookieDomain: localhost
      App__UseHttps: "false"
      Auth__CertificateConfigurationParameterName: /brighid/identity/signing-certificates
    labels:
      - traefik.enable=true
      - traefik.http.routers.adapter.rule=Host(`localhost`)
      - traefik.http.routers.adapter.entrypoints=web
      - traefik.http.services.adapter.loadbalancer.server.scheme=h2c

  db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    volumes:
      - my-db:/var/lib/mysql

  xray:
    image: public.ecr.aws/xray/aws-xray-daemon:latest
    command: -o
    volumes:
      - ~/.aws:/home/xray/.aws
    environment:
      AWS_REGION: us-east-1

volumes:
  my-db:
