Tags:
  Name: Brighid Identity
  Owner: Cythral
  Contact:Name: Talen Fisher
  Contact:Email: talen.fisher@cythral.com

Parameters:
  EnvironmentName:
    Development: dev
    Production: prod

  CookieDomain:
    Development: dev.brigh.id
    Production: brigh.id

  DatabaseHost:
    Development: db.dev.brigh.id
    Production: db.brigh.id

  DatabaseUser:
    Development: identity
    Production: identity

  DatabaseName:
    Development: identity
    Production: identity

  DatabasePassword:
    Development: AQICAHjCPp/4JJqnSjdP1A4JZ+E3yC2Gqmk9GshiMiqu57jujwH9ROD+MleLvYJKKFe0cXrwAAAAcjBwBgkqhkiG9w0BBwagYzBhAgEAMFwGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMMy+r0QrGB+/IRVaUAgEQgC8AaJ+noi1H+inOWfLLfQdXxN7KFh97jYeuZA6+atUVjq+vcikQ4PV/3Qj/RxzNVA==
    Production: AQICAHj/2SUStzyXNMLx0/GX2lnjChwPoR4BUvoYRIybQNwYyQHLN0/A3+6CyTxJKwxz1WmsAAAAcjBwBgkqhkiG9w0BBwagYzBhAgEAMFwGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMBRWaEelvFjKJWpKGAgEQgC9jdrJDOy4poC1Nkpgq8rgST4vTvjo+3O/fUFTeEvT2S+IdqcujUTtuCpiJczH2yQ==

  EnvoyImage:
    Development: 840364872350.dkr.ecr.us-east-1.amazonaws.com/aws-appmesh-envoy:v1.19.1.1-prod
    Production: 840364872350.dkr.ecr.us-east-1.amazonaws.com/aws-appmesh-envoy:v1.19.1.1-prod

  MeshNodeName:
    Development: commands-dev
    Production: commands-prod

  CertificateConfigurationParameterName:
    Development: /brighid/identity/signing-certificates
    Production: /brighid/identity/signing-certificates