Description: Brighid Identity
Parameters:
  Image:
    Type: String
    Description: Docker Image uri to pull

  DomainName:
    Type: String
    Description: Domain name to use

  EnableServiceStopping:
    Type: String
    AllowedValues:
      - "true"
      - "false"
    Description: Whether or not to enable service stopping on the cluster
  
  DatabaseName:
    Type: String
    Description: The name of the database to use

  DatabaseUser:
    Type: String
    Description: The name of the database user to use

  DatabasePassword:
    Type: String
    Description: The encrypted database password

Resources:
  DecryptedClientSecret:
    Type: Custom::Secret
    Properties:
      ServiceToken: !ImportValue cfn-secret-resource:SecretLambdaArn
      EncryptionRoleArn: !ImportValue cfn-secret-resource:EncryptionRoleArn
      Ciphertext: !ImportValue sso-aws:GoogleClientSecret

  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !ImportValue cfn-utilities:HttpListenerArn
      Priority: 5
      Actions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      Conditions:
        - Field: host-header
          HostHeaderConfig:
            Values:
              - !Ref DomainName

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      TargetType: ip
      VpcId: !ImportValue cfn-utilities:VpcId
      Protocol: HTTP
      Port: 80
      HealthCheckPath: /healthcheck
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: "30"

  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref AWS::StackName
      Tags:
        - Key: ENABLE_SERVICE_STOPPING
          Value: !Ref EnableServiceStopping

  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      ServiceName: !Ref AWS::StackName
      LaunchType: FARGATE
      EnableECSManagedTags: true
      PropagateTags: TASK_DEFINITION
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets: !Split
            - ","
            - !ImportValue cfn-utilities:SubnetIds
          SecurityGroups:
            - !ImportValue cfn-utilities:WebSecurityGroupId
          AssignPublicIp: ENABLED
      LoadBalancers:
        - ContainerName: !Ref AWS::StackName
          ContainerPort: 80
          TargetGroupArn: !Ref TargetGroup
      TaskDefinition: !Ref TaskDefinition
      DesiredCount: 1
      DeploymentConfiguration:
        MinimumHealthyPercent: 1
        MaximumPercent: 200

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Cpu: "256"
      Memory: "512"
      Family: !Ref AWS::StackName
      NetworkMode: awsvpc
      ExecutionRoleArn: !GetAtt TaskRole.Arn
      TaskRoleArn: !GetAtt TaskRole.Arn
      RequiresCompatibilities:
        - FARGATE
      ContainerDefinitions:
        - Name: !Ref AWS::StackName
          Essential: true
          Image: !Ref Image
          PortMappings:
            - ContainerPort: 80
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: !Ref AWS::StackName
          Environment:
            - Name: Database__Host
              Value: !ImportValue mutedac:ClusterAddress
            - Name: Database__Name
              Value: !Ref DatabaseName
            - Name: Database__User
              Value: !Ref DatabaseUser
            - Name: Encrypted__Database__Password
              Value: !Ref DatabasePassword
            - Name: EncryptionOptions__KmsKeyId
              Value: alias/SecretsKey


  ApplicationTopic:
    Type: AWS::SNS::Topic
    
  ApplicationTopicSubscription:
    Type: AWS::SNS::Subscription
    DependsOn:
      - Service
    Properties:
      Protocol: https
      TopicArn: !Ref ApplicationTopic
      Endpoint: !Sub https://${DomainName}/api/applications

  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role
        - !ImportValue cfn-utilities:SecretsKeyDecryptPolicyArn
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: ecs-tasks.amazonaws.com

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 14

Outputs:
  ApplicationTopicArn:
    Value: !Ref ApplicationTopic
    Description: ARN of the application topic used for creating/updating/deleting identity client applications.
    Export:
      Name: !Sub ${AWS::StackName}:ApplicationTopicArn