Description: Brighid Identity
Parameters:
  Image:
    Type: String
    Description: Docker Image uri to pull.

  DomainName:
    Type: String
    Description: Domain name to use.

  DatabaseHost:
    Type: String
    Description: The hostname of the database to use.

  DatabaseName:
    Type: String
    Description: The name of the database to use.

  DatabaseUser:
    Type: String
    Description: The name of the database user to use.

  DatabasePassword:
    Type: String
    Description: The encrypted database password.

  CookieDomain:
    Type: String
    Description: The domain name to use for the session cookie.

  EnvoyImage:
    Type: String
    Description: Image to use for the Envoy Sidecar.

  MeshNodeName:
    Type: String
    Description: Name to use for the node in the App Mesh.

  EnvironmentName:
    Type: String
    Description: Name to use for the environment.

  CertificateConfigurationParameterName:
    Type: String
    Description: Name of the parameter that contains certificate configuration.

Resources:
  MeshService:
    Type: AWS::AppMesh::VirtualService
    Properties:
      MeshName: brighid-mesh
      MeshOwner: !ImportValue cfn-metadata:SharedAccountId
      VirtualServiceName: !Ref DomainName
      Spec:
        Provider:
          VirtualNode:
            VirtualNodeName: !GetAtt MeshNode.VirtualNodeName

  MeshNode:
    Type: AWS::AppMesh::VirtualNode
    Properties:
      MeshName: brighid-mesh
      MeshOwner: !ImportValue cfn-metadata:SharedAccountId
      VirtualNodeName: !Ref MeshNodeName
      Spec:
        Listeners:
          - PortMapping:
              Port: 80
              Protocol: http2
            HealthCheck:
              UnhealthyThreshold: 3
              HealthyThreshold: 5
              TimeoutMillis: 30000
              Path: /healthcheck
              Protocol: http2
              IntervalMillis: 30000
        ServiceDiscovery:
          AWSCloudMap:
            NamespaceName: !ImportValue brighid-infrastructure:ServiceRegistryName
            ServiceName: identity

  MeshGatewayRoute:
    Type: Custom::MeshGatewayRoute
    Properties:
      ServiceToken: !ImportValue cfn-gateway-route-resource:GatewayRouteLambdaArn
      MeshName: brighid-mesh
      MeshOwner: !ImportValue cfn-metadata:SharedAccountId
      VirtualGatewayName: internet
      GatewayRouteName: !Ref MeshNodeName
      Spec:
        Http2Route:
          Action:
            Target:
              VirtualService:
                VirtualServiceName: !GetAtt MeshService.VirtualServiceName
          Match:
            Prefix: /
            Hostname:
              Exact: !Ref DomainName

  ServiceRegistryRecord:
    Type: AWS::ServiceDiscovery::Service
    Properties: 
      Description: Internal Discovery Service for Brighid
      DnsConfig:
        RoutingPolicy: MULTIVALUE
        DnsRecords:
          - TTL: 60
            Type: A
          - TTL: 60
            Type: SRV
      HealthCheckCustomConfig:
        FailureThreshold: 1
      NamespaceId: !ImportValue brighid-infrastructure:ServiceRegistry
      Name: identity

  DecryptedClientSecret:
    Type: Custom::Secret
    Properties:
      ServiceToken: !ImportValue cfn-secret-resource:SecretLambdaArn
      EncryptionRoleArn: !ImportValue cfn-secret-resource:EncryptionRoleArn
      Ciphertext: !ImportValue sso-aws:GoogleClientSecret

  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !ImportValue brighid-infrastructure:ClusterName
      ServiceName: identity
      LaunchType: FARGATE
      EnableECSManagedTags: true
      PropagateTags: TASK_DEFINITION
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets: !Split
            - ","
            - !ImportValue cfn-utilities:SubnetIds
          SecurityGroups:
            - !ImportValue cfn-utilities:WebSecurityGroupId
            - !ImportValue cfn-utilities:EnvoySecurityGroupId
          AssignPublicIp: ENABLED
      ServiceRegistries:
        - RegistryArn: !GetAtt ServiceRegistryRecord.Arn
          Port: 80
      TaskDefinition: !Ref TaskDefinition
      DesiredCount: 1
      DeploymentConfiguration:
        MinimumHealthyPercent: 1
        MaximumPercent: 200
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: true

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Cpu: "256"
      Memory: "512"
      Family: !Ref AWS::StackName
      NetworkMode: awsvpc
      ExecutionRoleArn: !GetAtt TaskRole.Arn
      TaskRoleArn: !GetAtt TaskRole.Arn
      RequiresCompatibilities:
        - FARGATE
      ProxyConfiguration:
        Type: APPMESH
        ContainerName: envoy
        ProxyConfigurationProperties:
          - Name: IgnoredUID
            Value: "1337"
          - Name: ProxyIngressPort
            Value: "15000"
          - Name: ProxyEgressPort
            Value: "15001"
          - Name: AppPorts
            Value: "80"
          - Name: EgressIgnoredIPs
            Value: 169.254.170.2,169.254.169.254
      ContainerDefinitions:
        - Name: !Ref AWS::StackName
          Essential: true
          Image: !Ref Image
          DependsOn:
            - ContainerName: envoy
              Condition: HEALTHY
          PortMappings:
            - ContainerPort: 80
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: brighid
          Environment:
            - Name: Database__Host
              Value: !Ref DatabaseHost
            - Name: Database__Name
              Value: !Ref DatabaseName
            - Name: Database__User
              Value: !Ref DatabaseUser
            - Name: Encrypted__Database__Password
              Value: !Ref DatabasePassword
            - Name: EncryptionOptions__KmsKeyId
              Value: alias/SecretsKey
            - Name: Auth__DomainName
              Value: !Ref DomainName
            - Name: Auth__CookieDomain
              Value: !Ref CookieDomain
            - Name: Network__InternalIpv4Cidr
              Value: !ImportValue cfn-utilities:Ipv4NetworkCidr
            - Name: App__WaitConditionHandle
              Value: !Ref WaitConditionHandle
            - Name: App__Image
              Value: !Ref Image
            - Name: Environment__Name
              Value: !Ref EnvironmentName
            - Name: Auth__CertificateConfigurationParameterName
              Value: !Ref CertificateConfigurationParameterName
        - Name: envoy
          Image: !Ref EnvoyImage
          Essential: true
          User: "1337"
          Ulimits:
            - Name: nofile
              HardLimit: 15000
              SoftLimit: 15000
          PortMappings:
            - ContainerPort: 9901
            - ContainerPort: 15000
            - ContainerPort: 15001
          HealthCheck:
            Command:
              - CMD-SHELL
              - curl -s http://localhost:9901/server_info | grep state | grep -q LIVE
            Interval: 5
            Timeout: 2
            Retries: 3
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: brighid
          Environment:
            - Name: APPMESH_RESOURCE_ARN
              Value: !Sub
                - mesh/brighid-mesh@${SharedAccountId}/virtualNode/${MeshNode.VirtualNodeName}
                - SharedAccountId: !ImportValue cfn-metadata:SharedAccountId
                  
  WaitConditionHandle:
    Type: AWS::CloudFormation::WaitConditionHandle
      
  WaitCondition:
    Type: AWS::CloudFormation::WaitCondition
    DependsOn: Service
    Properties:
      Count: 1
      Handle: !Ref WaitConditionHandle
      Timeout: "300"

  WaitConditionSignal:
    Type: Custom::JsonValue
    Properties:
      ServiceToken: !ImportValue cfn-json-value-resource:JsonValueLambdaArn
      Json: !GetAtt WaitCondition.Data
      Key: SeededApplication

  ApplicationTopic:
    Type: AWS::SNS::Topic
  
  ApplicationTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sns:Publish
            Resource: "*"
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AWS::AccountId}:root
                - !Sub 
                  - arn:aws:iam::${MasterAccountId}:root
                  - MasterAccountId: !ImportValue cfn-utilities:MasterAccountId
      Topics:
        - !Ref ApplicationTopic

  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        - arn:aws:iam::aws:policy/AWSAppMeshEnvoyAccess
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role
        - !ImportValue cfn-utilities:SecretsKeyDecryptPolicyArn
        - !ImportValue cfn-utilities:SecretsKeyEncryptPolicyArn
        - !ImportValue identity-certificates:CertificateReadPolicyArn
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: ecs-tasks.amazonaws.com

  TaskPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Roles:
        - !Ref TaskRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: ssm:GetParameter
            Resource: 
              - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/brighid/*/account-link/start-url

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /brighid/identity
      RetentionInDays: 14

Outputs:
  CloudFormationApplicationClientId:
    Value: !Select [0, !Split ["\n", !GetAtt WaitConditionSignal.Result]]
    Description: Client ID of the CloudFormation Brighid Identity Application
  
  CloudFormationApplicationEncryptedSecret:
    Value: !Select [1, !Split ["\n", !GetAtt WaitConditionSignal.Result]]
    Description: Encrypted Client Secret of the CloudFormation Brighid Identity Application

  ApplicationTopicArn:
    Value: !Ref ApplicationTopic
    Description: ARN of the application topic used for creating/updating/deleting identity client applications.
    Export:
      Name: !Sub ${AWS::StackName}:ApplicationTopicArn